// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8S7P1aAXOU11H7VGPkPc53I_RGEybY7s',
    appId: '1:1089069778067:web:34167fea5c094b2e9db966',
    messagingSenderId: '1089069778067',
    projectId: 'newproject-12964',
    authDomain: 'newproject-12964.firebaseapp.com',
    storageBucket: 'newproject-12964.firebasestorage.app',
    measurementId: 'G-YHW62E8WVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dH0vZZxn6Q5mhMo0LoBN5pwT3-oVLsk',
    appId: '1:1089069778067:android:a0df50b3feff1ac99db966',
    messagingSenderId: '1089069778067',
    projectId: 'newproject-12964',
    storageBucket: 'newproject-12964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcxijhtPNobLIbSDyqkCYm5QHdlgXZJcQ',
    appId: '1:1089069778067:ios:8250639fb907a15a9db966',
    messagingSenderId: '1089069778067',
    projectId: 'newproject-12964',
    storageBucket: 'newproject-12964.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcxijhtPNobLIbSDyqkCYm5QHdlgXZJcQ',
    appId: '1:1089069778067:ios:8250639fb907a15a9db966',
    messagingSenderId: '1089069778067',
    projectId: 'newproject-12964',
    storageBucket: 'newproject-12964.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8S7P1aAXOU11H7VGPkPc53I_RGEybY7s',
    appId: '1:1089069778067:web:9bd23fb35ad9e9759db966',
    messagingSenderId: '1089069778067',
    projectId: 'newproject-12964',
    authDomain: 'newproject-12964.firebaseapp.com',
    storageBucket: 'newproject-12964.firebasestorage.app',
    measurementId: 'G-F946SQ8NBC',
  );

}